"""License key system for Pro features — simple and pragmatic.

Keys are HMAC-based: base64(version:email:expiry:hmac).
Generated by: echo "v1:user@email.com:2026-12-31" | openssl dgst -sha256 -hmac "secret"
Real deployments should use a proper server, but this works for a sellable CLI tool.
"""

from __future__ import annotations

import hashlib
import hmac
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

# ── Key format ──────────────────────────────────────────────────────
# version:email:expiry_date:signature
# signature = HMAC-SHA256(version:email:expiry, secret)

_LICENSE_SECRET = b"apo-pro-2024-nous-research-secret-key-v1"

LICENSE_FILE_PATHS = [
    Path.home() / ".apo_license",
    Path("/etc/apo_license"),
]


@dataclass
class LicenseInfo:
    """Parsed license information."""

    valid: bool
    email: str = ""
    expiry_date: str = ""
    days_remaining: int = 0
    error: str = ""


def _compute_signature(data: str) -> str:
    """Compute HMAC-SHA256 signature."""
    return hmac.new(_LICENSE_SECRET, data.encode(), hashlib.sha256).hexdigest()[:16]


def generate_license(email: str, expiry_date: str) -> str:
    """Generate a license key for a given email and expiry date (YYYY-MM-DD)."""
    payload = f"v1:{email}:{expiry_date}"
    sig = _compute_signature(payload)
    return f"{payload}:{sig}"


def parse_license(key: str) -> LicenseInfo:
    """Parse and validate a license key."""
    parts = key.strip().split(":")
    if len(parts) != 4:
        return LicenseInfo(valid=False, error="Invalid key format")

    version, email, expiry, signature = parts
    if version != "v1":
        return LicenseInfo(valid=False, error="Unknown key version")

    payload = f"v1:{email}:{expiry}"
    expected = _compute_signature(payload)

    if not hmac.compare_digest(signature, expected):
        return LicenseInfo(valid=False, error="Invalid signature — key may be tampered")

    # Check expiry
    try:
        expiry_ts = time.mktime(time.strptime(expiry, "%Y-%m-%d"))
        now = time.time()
        days_remaining = int((expiry_ts - now) / 86400)

        if days_remaining < 0:
            return LicenseInfo(
                valid=False,
                email=email,
                expiry_date=expiry,
                days_remaining=days_remaining,
                error=f"License expired {abs(days_remaining)} days ago",
            )
    except ValueError:
        return LicenseInfo(valid=False, error="Invalid expiry date format")

    return LicenseInfo(
        valid=True,
        email=email,
        expiry_date=expiry,
        days_remaining=days_remaining,
    )


def find_license() -> Optional[str]:
    """Search for a license file in standard locations."""
    for path in LICENSE_FILE_PATHS:
        if path.exists():
            return path.read_text().strip()
    return None


def check_pro_access() -> LicenseInfo:
    """Check if Pro features are unlocked. Returns LicenseInfo."""
    key = find_license()
    if not key:
        return LicenseInfo(
            valid=False,
            error="No license found. Get one at https://promptoptimizer.dev/pro",
        )
    return parse_license(key)


def save_license(key: str, path: Optional[Path] = None) -> Path:
    """Save a license key to disk."""
    if path is None:
        path = Path.home() / ".apo_license"
    path.write_text(key.strip())
    path.chmod(0o600)
    return path
